name: sentinel2py-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.24
  - rasterio>=1.3
  - matplotlib>=3.7
  - scikit-image>=0.21
  - pandas>=2.0
  - tqdm>=4.65
  - pip
  - pip:
      - pystac-client>=0.6
      - planetary-computer>=0.3
