[project]
name = "sentinel2py"
version = "0.1.0"
description = "A Python library to read, process and analyse Sentinel-2 imagery"
authors = [{ name="Emanuele Capizzi" }]
requires-python = ">=3.8"
license = "MIT"
